[
    {
        "news_id": "news27ed822ec3547a3fc983385da9bed052",
        "cat_id": "catc89337f32ce2dc3f6fcdbcd1d1c54350",
        "user_id": "c4ca4238a0b923820dcc509a6f75849b",
        "news_title": "Technology 5 - Mauris nec massa accumsan, ornare est sed, commodo quam.",
        "news_desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed ligula sed diam placerat hendrerit. Aliquam dignissim libero in tellus hendrerit vulputate. Pellentesque sodales erat ut nunc scelerisque egestas. Nunc sed lorem sit amet lacus tempor viverra et sit amet eros. Quisque bibendum, felis eget suscipit mattis, orci dui pretium risus, non laoreet dui lectus nec lorem. Nam ac lectus vel odio lobortis tincidunt et at magna. Donec quis enim in nisi ornare finibus non luctus purus. Quisque sodales euismod pellentesque. 123",
        "news_is_published": "1",
        "news_is_editor_pick": "1",
        "news_search_tags": "Technology",
        "seo_title": "Technology SEO Title",
        "seo_desc": "Nam ac lectus vel odio lobortis tincidunt et at magna. Donec quis enim in nisi ornare finibus non luctus purus. Quisque sodales euismod pellentesque.",
        "seo_keywords": "technology, panacea-soft, seo",
        "added_date": "2 years ago",
        "added_date_str": "2018-01-25 09:16:44",
        "default_photo": {
            "img_id": "img4f2c6d8b38db3f5e2ca22917bc82dfde",
            "img_parent_id": "news27ed822ec3547a3fc983385da9bed052",
            "img_type": "news",
            "img_path": "tech8.png",
            "Img_width": "600",
            "img_height": "400",
            "img_desc": "desc 2"
        },
        "default_youtube": {
            "news_youtube_id": "newsyoutubecf384c77ce8fb62a5d33c364dc05db0c",
            "news_id": "news27ed822ec3547a3fc983385da9bed052",
            "news_youtube_url": "R2Xbo-irtBA",
            "added_date": "2018-01-25 09:16:44"
        },
        "category": {
            "cat_id": "catc89337f32ce2dc3f6fcdbcd1d1c54350",
            "cat_name": "Technology",
            "cat_ordering": "9",
            "cat_is_published": "1",
            "added_date": "2017-11-22 22:18:30",
            "default_photo": {
                "img_id": "imgdfd9f5a6dff02ebd0ef23629bf2a6697",
                "img_parent_id": "catc89337f32ce2dc3f6fcdbcd1d1c54350",
                "img_type": "category",
                "img_path": "Cover18.png",
                "Img_width": "600",
                "img_height": "400",
                "img_desc": ""
            },
            "user_selected": "false"
        },
        "like_count": "0",
        "comment_count": "0",
        "favourite_count": "0",
        "touch_count": "4",
        "youtube_count": "1",
        "image_count": "2",
        "is_user_liked": "false",
        "is_user_favourited": "false"
    },
    {
        "news_id": "news1fe3c8214a54d4bb883f8a39d02988b1",
        "cat_id": "cataac89da8f95cbe9b3e4c656cfac0d2f8",
        "user_id": "c4ca4238a0b923820dcc509a6f75849b",
        "news_title": "Commentary 9 - Mauris nec massa accumsan, ornare est sed, commodo quam.",
        "news_desc": "Vivamus lectus ante, pulvinar vitae ante eget, consectetur vestibulum dolor. In hac habitasse platea dictumst. Nunc elementum facilisis neque non finibus. Integer maximus arcu vitae lectus finibus luctus id in sapien. Nullam pellentesque varius enim vitae ultrices. Mauris pellentesque, felis vel scelerisque tempor, magna neque luctus ligula, at cursus mi ante in augue. Etiam condimentum lectus vitae felis ullamcorper dapibus. Nulla vulputate odio lacus, et vulputate nibh mattis eu. Aenean ac pretium sapien. Cras ipsum arcu, convallis ac sagittis vel, tincidunt in sem.",
        "news_is_published": "1",
        "news_is_editor_pick": "1",
        "news_search_tags": "commentary",
        "seo_title": "Business SEO Title",
        "seo_desc": "Vivamus lectus ante, pulvinar vitae ante eget, consectetur vestibulum dolor. In hac habitasse platea dictumst. Nunc elementum facilisis neque non finibus.",
        "seo_keywords": "business, panacea-soft, seo",
        "added_date": "2 years ago",
        "added_date_str": "2018-01-25 02:29:49",
        "default_photo": {
            "img_id": "img0fb9847315dcfd5e8c4b955c529e4a59",
            "img_parent_id": "news1fe3c8214a54d4bb883f8a39d02988b1",
            "img_type": "news",
            "img_path": "comment9(1).png",
            "Img_width": "600",
            "img_height": "400",
            "img_desc": "desc 1"
        },
        "default_youtube": {
            "news_youtube_id": "newsyoutubea9899e1924d490a67e8f6e0eedd35730",
            "news_id": "news1fe3c8214a54d4bb883f8a39d02988b1",
            "news_youtube_url": "AntcyqJ6brc",
            "added_date": "2018-01-25 08:33:38"
        },
        "category": {
            "cat_id": "cataac89da8f95cbe9b3e4c656cfac0d2f8",
            "cat_name": "Commentary",
            "cat_ordering": "2",
            "cat_is_published": "1",
            "added_date": "2017-12-02 22:19:03",
            "default_photo": {
                "img_id": "img9591b14020f0bd2c1b9abc1c5a7e8881",
                "img_parent_id": "cataac89da8f95cbe9b3e4c656cfac0d2f8",
                "img_type": "category",
                "img_path": "Cover11.png",
                "Img_width": "600",
                "img_height": "400",
                "img_desc": ""
            },
            "user_selected": "false"
        },
        "like_count": "1",
        "comment_count": "1",
        "favourite_count": "1",
        "touch_count": "6",
        "youtube_count": "2",
        "image_count": "2",
        "is_user_liked": "false",
        "is_user_favourited": "false"
    },
    {
        "news_id": "news129401968ab60e79f69186839a45b06e",
        "cat_id": "cat7bd5806ed94661108946e2f7742907c2",
        "user_id": "c4ca4238a0b923820dcc509a6f75849b",
        "news_title": "Business 1 - Mauris nec massa accumsan, ornare est sed, commodo quam.",
        "news_desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed ligula sed diam placerat hendrerit. Aliquam dignissim libero in tellus hendrerit vulputate. Pellentesque sodales erat ut nunc scelerisque egestas. Nunc sed lorem sit amet lacus tempor viverra et sit amet eros. Quisque bibendum, felis eget suscipit mattis, orci dui pretium risus, non laoreet dui lectus nec lorem. Nam ac lectus vel odio lobortis tincidunt et at magna. Donec quis enim in nisi ornare finibus non luctus purus. Quisque sodales euismod pellentesque.",
        "news_is_published": "1",
        "news_is_editor_pick": "0",
        "news_search_tags": "business",
        "seo_title": "Business SEO Title",
        "seo_desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed ligula sed diam placerat hendrerit. Aliquam dignissim libero in tellus hendrerit vulputate.",
        "seo_keywords": "business, panacea-soft, seo",
        "added_date": "2 years ago",
        "added_date_str": "2018-01-25 02:28:49",
        "default_photo": {
            "img_id": "img23e7a823ffac8bff95f3fdadcf3f12c8",
            "img_parent_id": "news129401968ab60e79f69186839a45b06e",
            "img_type": "news",
            "img_path": "business1.png",
            "Img_width": "600",
            "img_height": "400",
            "img_desc": "test 1"
        },
        "default_youtube": {
            "news_youtube_id": "newsyoutubee5e0a0e5c4e6887cc584374d74936552",
            "news_id": "news129401968ab60e79f69186839a45b06e",
            "news_youtube_url": "R2Xbo-irtBA",
            "added_date": "2018-01-25 02:28:49"
        },
        "category": {
            "cat_id": "cat7bd5806ed94661108946e2f7742907c2",
            "cat_name": "Business",
            "cat_ordering": "1",
            "cat_is_published": "1",
            "added_date": "2017-12-02 22:18:18",
            "default_photo": {
                "img_id": "imgbec65f37f48d51a23546972e9c664b8b",
                "img_parent_id": "cat7bd5806ed94661108946e2f7742907c2",
                "img_type": "category",
                "img_path": "cover1.png",
                "Img_width": "600",
                "img_height": "400",
                "img_desc": ""
            },
            "user_selected": "false"
        },
        "like_count": "0",
        "comment_count": "0",
        "favourite_count": "0",
        "touch_count": "3",
        "youtube_count": "1",
        "image_count": "3",
        "is_user_liked": "false",
        "is_user_favourited": "false"
    },
    {
        "news_id": "news28d19d55c00a959f34f7e34ce78a826c",
        "cat_id": "cat5a770d139ce93876fa4b140e6598e179",
        "user_id": "c4ca4238a0b923820dcc509a6f75849b",
        "news_title": "Politics 3 - Mauris nec massa accumsan, ornare est sed, commodo quam.",
        "news_desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed ligula sed diam placerat hendrerit. Aliquam dignissim libero in tellus hendrerit vulputate. Pellentesque sodales erat ut nunc scelerisque egestas. Nunc sed lorem sit amet lacus tempor viverra et sit amet eros. Quisque bibendum, felis eget suscipit mattis, orci dui pretium risus, non laoreet dui lectus nec lorem. Nam ac lectus vel odio lobortis tincidunt et at magna. Donec quis enim in nisi ornare finibus non luctus purus. Quisque sodales euismod pellentesque.",
        "news_is_published": "1",
        "news_is_editor_pick": "1",
        "news_search_tags": "Politics",
        "seo_title": "Politics SEO Title",
        "seo_desc": "Donec quis enim in nisi ornare finibus non luctus purus. Quisque sodales euismod pellentesque.",
        "seo_keywords": "politics, panacea-soft, seo",
        "added_date": "2 years ago",
        "added_date_str": "2018-01-02 01:59:06",
        "default_photo": {
            "img_id": "img8d50d29c3d241b937635ececb7aea388",
            "img_parent_id": "news28d19d55c00a959f34f7e34ce78a826c",
            "img_type": "news",
            "img_path": "politics3(1).png",
            "Img_width": "600",
            "img_height": "400",
            "img_desc": "desc 1"
        },
        "default_youtube": {
            "news_youtube_id": "newsyoutubee6da1474f6ac90d9da4ad3dd217baf65",
            "news_id": "news28d19d55c00a959f34f7e34ce78a826c",
            "news_youtube_url": "AntcyqJ6brc",
            "added_date": "2018-01-02 01:59:06"
        },
        "category": {
            "cat_id": "cat5a770d139ce93876fa4b140e6598e179",
            "cat_name": "Politics",
            "cat_ordering": "6",
            "cat_is_published": "1",
            "added_date": "2017-12-02 22:24:07",
            "default_photo": {
                "img_id": "img1843861b7547b14dca8925eff9c547fa",
                "img_parent_id": "cat5a770d139ce93876fa4b140e6598e179",
                "img_type": "category",
                "img_path": "Cover15.png",
                "Img_width": "600",
                "img_height": "400",
                "img_desc": ""
            },
            "user_selected": "false"
        },
        "like_count": "0",
        "comment_count": "0",
        "favourite_count": "0",
        "touch_count": "0",
        "youtube_count": "1",
        "image_count": "2",
        "is_user_liked": "false",
        "is_user_favourited": "false"
    },
    {
        "news_id": "news5f371c76168842348306fb82ad27af20",
        "cat_id": "catc89337f32ce2dc3f6fcdbcd1d1c54350",
        "user_id": "c4ca4238a0b923820dcc509a6f75849b",
        "news_title": "Technology 8 - Cras molestie iaculis diam, non pellentesque purus ornare eu.",
        "news_desc": "Vivamus lectus ante, pulvinar vitae ante eget, consectetur vestibulum dolor. In hac habitasse platea dictumst. Nunc elementum facilisis neque non finibus. Integer maximus arcu vitae lectus finibus luctus id in sapien. Nullam pellentesque varius enim vitae ultrices. Mauris pellentesque, felis vel scelerisque tempor, magna neque luctus ligula, at cursus mi ante in augue. Etiam condimentum lectus vitae felis ullamcorper dapibus. Nulla vulputate odio lacus, et vulputate nibh mattis eu. Aenean ac pretium sapien. Cras ipsum arcu, convallis ac sagittis vel, tincidunt in sem.",
        "news_is_published": "1",
        "news_is_editor_pick": "1",
        "news_search_tags": "Technology",
        "seo_title": "Technology SEO Title",
        "seo_desc": "Cras ipsum arcu, convallis ac sagittis vel, tincidunt in sem.",
        "seo_keywords": "technology, panacea-soft, seo",
        "added_date": "2 years ago",
        "added_date_str": "2018-01-02 01:57:57",
        "default_photo": {
            "img_id": "img00a259289f4b30cfbcdba825b0a17458",
            "img_parent_id": "news5f371c76168842348306fb82ad27af20",
            "img_type": "news",
            "img_path": "tech8(2).png",
            "Img_width": "600",
            "img_height": "400",
            "img_desc": "desc 1"
        },
        "default_youtube": {
            "news_youtube_id": "newsyoutubef3c21e0a4d8e7fec59612eae46b3127c",
            "news_id": "news5f371c76168842348306fb82ad27af20",
            "news_youtube_url": "R2Xbo-irtBA",
            "added_date": "2018-01-02 01:58:56"
        },
        "category": {
            "cat_id": "catc89337f32ce2dc3f6fcdbcd1d1c54350",
            "cat_name": "Technology",
            "cat_ordering": "9",
            "cat_is_published": "1",
            "added_date": "2017-11-22 22:18:30",
            "default_photo": {
                "img_id": "imgdfd9f5a6dff02ebd0ef23629bf2a6697",
                "img_parent_id": "catc89337f32ce2dc3f6fcdbcd1d1c54350",
                "img_type": "category",
                "img_path": "Cover18.png",
                "Img_width": "600",
                "img_height": "400",
                "img_desc": ""
            },
            "user_selected": "false"
        },
        "like_count": "0",
        "comment_count": "0",
        "favourite_count": "0",
        "touch_count": "1",
        "youtube_count": "1",
        "image_count": "2",
        "is_user_liked": "false",
        "is_user_favourited": "false"
    }
]
